apiVersion: v1
kind: ServiceAccount
metadata:
  name: xhomer-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xhomer-cluster-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xhomer-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xhomer-cluster-role
subjects:
  - kind: ServiceAccount
    name: xhomer-service-account
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xhomer-deployment
spec:
  selector:
    matchLabels:
      app: xhomer
  template:
    metadata:
      labels:
        app: xhomer
    spec:
      serviceAccountName: xhomer-service-account
      containers:
        - name: xhomer
          image: xenedium/xhomer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: xhomer-service
spec:
  selector:
    app: xhomer
  ports:
    - port: 8080
      targetPort: 8080
