apiVersion: apps/v1
kind: Deployment
metadata:
  name: xhomer-deployment
spec:
  selector:
    matchLabels:
      app: xhomer
  template:
    metadata:
      labels:
        app: xhomer
    spec:
      containers:
      - name: xhomer
        image: xenedium/xhomer:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: xhomer-service
spec:
  selector:
    app: xhomer
  ports:
  - port: 8080
    targetPort: 8080

